### PR TITLE
[2.x] #285 Fix (Update All Button not being disabled correctly), #177 Addition (Language Selection), #294 (View in Browser Button)

### LINKED ISSUE #177: Add a switch for language in app
It picks up my system locale (which is en-us), but I want to see it in my language instead

### LINKED ISSUE #285: [2.x] Update All Button not disabled on "My Addons" Page for different Clients
Seems the "Update All" disabled function doesn't work on all Clients/Channels

My Addons Page (Retail):
image

My Addons Page (Beta):
image

### LINKED ISSUE #294: [2.x] "View in browser" button looks like inactive
"View in browser" button looks like inactive.

image

### PR DESCRIPTION
**Pull request by Cratis1831**
Close #285 
Update All button was still showing enabled even if there were no addons to update

Issue:
if there is an addon that is set to "ignored" but underlying has an update the "Update All" button will be enabled
so if you uncheck the ignore and update the addon
then the "Update All" button will get disabled

Close #177 
Add function to switch languages

Close #294
Re-design the details page a bit

### CODE REVIEW

File: wowup-electron/src/app/pages/my-addons/my-addons.component.ts [hunk 1]
```diff
@@ -207,7 +207,7 @@ export class MyAddonsComponent implements OnInit, OnDestroy {
         console.debug("sortedListItems", sortedListItems);
         this.sortedListItems = sortedListItems;
         this.enableUpdateAll = this.sortedListItems.some(
-          (li) => li.needsInstall || li.needsUpdate
+          (li) => (li.needsInstall || li.needsUpdate) && !li.isIgnored
```
Comment (MadenBot) [inline wowup-electron/src/app/pages/my-addons/my-addons.component.ts:210]: Not sure of the order of evaluation - but potential **very** minor optimization could be to move `!li.isIgnored` before the OR check. As it potentially doesn't need to evaluate the OR.

File: wowup-electron/src/app/components/options-app-section/options-app-section.component.ts [hunk 2]
```diff
@@ -48,6 +51,8 @@ export class OptionsAppSectionComponent implements OnInit {
     this.useHardwareAcceleration = this.wowupService.useHardwareAcceleration;
     this.startWithSystem = this.wowupService.startWithSystem;
     this.startMinimized = this.wowupService.startMinimized;
+    this.setCurrentLanguage = this.wowupService.setCurrentLanguage;
```
Comment (jliddev) [inline wowup-electron/src/app/components/options-app-section/options-app-section.component.ts:54]: this.setCurrentLanguage should be this.currentLanguage?

File: wowup-electron/src/app/components/options-app-section/options-app-section.component.ts [hunk 3]
```diff
@@ -99,4 +104,27 @@ export class OptionsAppSectionComponent implements OnInit {
       this._electronService.restartApplication();
     });
   };
+
+  onSetCurrentLanguageChange = (evt: MatSelectChange) => {
```
Comment (jliddev) [inline wowup-electron/src/app/components/options-app-section/options-app-section.component.ts:108]: onCurrentLanguageChange

File: wowup-electron/src/app/components/options-app-section/options-app-section.component.html [hunk 4]
```diff
@@ -28,53 +43,143 @@ <h2>
...
+        appUserActionTracker
+        category="Options"
+        action="StartMinimized"
+        [label]="startMinimized"
+      >
       </mat-slide-toggle>
     </div>
   </div>
+  <!-- SET LANGUAGE -->
+  <div class="toggle">
```
Comment (jliddev) [inline wowup-electron/src/app/components/options-app-section/options-app-section.component.html:144]: Maybe we move this to the top?

File: wowup-electron/src/common/constants.ts [hunk 5]
```diff
@@ -31,6 +31,7 @@ export const START_MINIMIZED_PREFERENCE_KEY = "start_minimized";
 export const NO_SEARCH_RESULTS_ERROR = "NO_SEARCH_RESULTS";
 export const NO_LATEST_SEARCH_RESULT_FILES_ERROR =
   "NO_LATEST_SEARCH_RESULT_FILES";
+export const SET_LANGUAGE_PREFERENCE_KEY = "set_language";
```
Comment (jliddev) [inline wowup-electron/src/common/constants.ts:34]: would selected_language make more sense?

File: wowup-electron/src/app/app.component.ts [hunk 6]
```diff
@@ -38,9 +38,21 @@ export class AppComponent implements AfterViewInit {
...
+      "ko",
+      "nb",
+      "pt",
+      "ru",
+      "zh",
+    ]);
     this.translate.setDefaultLang("en");
-
     this.translate.use(this._electronService.locale);
+    this.translate.use(this._wowUpService.setCurrentLanguage);
```
Comment (jliddev) [inline wowup-electron/src/app/app.component.ts:55]: what happens if this pref has not been set yet?

**Review by jliddev — CHANGES_REQUESTED** [review]
Some minor naming changes.
Maybe move the language selector to the top?
We need to initialize the preference to the current locale

File: wowup-electron/src/app/pages/my-addons/my-addons.component.ts (hunk 1 above)
Comment (Cratis1831) [reply wowup-electron/src/app/pages/my-addons/my-addons.component.ts:210]: @MadenBot thx, made the change

**Review by jliddev — APPROVED** [review]
