### PR TITLE
[2.x] Fix: Language Selector Bugs

### LINKED ISSUE #310: [2.x] Language Selector Issues
- Language selector not able to select English in non-English locale OS
- Language selector dialog when "No" button is selected, doesn't set language in dropdown back to original value

### PR DESCRIPTION
**Pull request by Cratis1831**
Close #310 
- Fixed: Language selector not able to select English in non-English locale OS
- Fixed: Language selector dialog when "No" button is selected, doesn't set language in dropdown back to original value

- Add: Localized the language selector list
- Add: Missing entry for "CURRENT_LANGUAGE_LABEL" in language files

### CODE REVIEW

File: wowup-electron/src/app/app.component.ts [hunk 1]
```diff
@@ -38,20 +40,13 @@ export class AppComponent implements AfterViewInit {
...
-      "fr",
-      "it",
-      "ko",
-      "nb",
-      "pt",
-      "ru",
-      "zh",
-    ]);
+    this._fileService
+      .listFiles("./src/assets/i18n/", "*.json")
```
Comment (jliddev) [inline wowup-electron/src/app/app.component.ts:44]: This path will not work when the app is published.

Comment (Cratis1831) [reply wowup-electron/src/app/app.component.ts]: rolled back to hardcoded language list

**Review by jliddev — APPROVED** [review]
